// Mock data for admin dashboard
// NOTE: Replace with API calls to backend for production

export interface User {
  id: string;
  name: string;
  email: string;
  phone: string;
  level: number;
  levelName: string;
  avatar: string;
  wallet: number;
  bonus: number;
  tickets: number;
  referrals: number;
  kycStatus: 'Verified' | 'Pending' | 'Rejected';
  status: 'Active' | 'Suspended' | 'VIP';
  joinedDate: Date;
  points: number;
  nextLevelPoints: number;
  totalSpent: number;
}

export interface Draw {
  id: string;
  name: string;
  gameType: string;
  prizePool: number;
  ticketPrice: number;
  maxEntries: number;
  entries: number;
  status: 'live' | 'scheduled' | 'completed' | 'draft';
  drawDate: Date;
  eligibleLevels: number[];
  description: string;
  winnerId?: string;
  winnerName?: string;
}

export interface Transaction {
  id: string;
  userId: string;
  userName: string;
  method: 'UPI' | 'Card' | 'NetBanking' | 'Wallet';
  amount: number;
  type: 'Deposit' | 'Withdrawal' | 'TicketPurchase' | 'PrizePayout';
  status: 'Success' | 'Pending' | 'Failed';
  datetime: Date;
  note: string;
}

export interface KYCDocument {
  id: string;
  userId: string;
  userName: string;
  email: string;
  docType: 'Aadhaar' | 'PAN' | 'Passport' | 'VoterID';
  submittedAt: Date;
  docUrl: string;
  selfieUrl: string;
}

export interface Notification {
  id: string;
  icon: string;
  title: string;
  audience: string;
  channels: string[];
  sentCount: number;
  openRate: number;
  clickRate: number;
  sentAt: Date;
  status: string;
}

export interface AdminLog {
  id: string;
  adminName: string;
  action: string;
  target: string;
  datetime: Date;
  ip: string;
}

export interface Level {
  level: number;
  name: string;
  color: string;
  users: number;
  pointsMin: number;
  pointsMax: number;
  perks: string[];
  discount: number;
  picks: number;
}

// Users Data - 50 users with Indian names
export const users: User[] = [
  {
    id: '1',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@email.com',
    phone: '+91 9876543210',
    level: 4,
    levelName: 'Gold',
    avatar: 'R',
    wallet: 4200,
    bonus: 500,
    tickets: 24,
    referrals: 3,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-23'),
    points: 2400,
    nextLevelPoints: 10000,
    totalSpent: 12000,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91 9876543211',
    level: 3,
    levelName: 'Silver',
    avatar: 'P',
    wallet: 1800,
    bonus: 200,
    tickets: 12,
    referrals: 1,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-20'),
    points: 450,
    nextLevelPoints: 10000,
    totalSpent: 5400,
  },
  {
    id: '3',
    name: 'Amit Singh',
    email: 'amit.singh@email.com',
    phone: '+91 9876543212',
    level: 2,
    levelName: 'Bronze',
    avatar: 'A',
    wallet: 900,
    bonus: 100,
    tickets: 6,
    referrals: 0,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-18'),
    points: 120,
    nextLevelPoints: 10000,
    totalSpent: 2700,
  },
  {
    id: '4',
    name: 'Sneha Patel',
    email: 'sneha.patel@email.com',
    phone: '+91 9876543213',
    level: 5,
    levelName: 'Platinum',
    avatar: 'S',
    wallet: 8400,
    bonus: 1200,
    tickets: 38,
    referrals: 8,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-12-16'),
    points: 5600,
    nextLevelPoints: 10000,
    totalSpent: 25200,
  },
  {
    id: '5',
    name: 'Kiran Rao',
    email: 'kiran.rao@email.com',
    phone: '+91 9876543214',
    level: 1,
    levelName: 'Basic',
    avatar: 'K',
    wallet: 300,
    bonus: 0,
    tickets: 2,
    referrals: 0,
    kycStatus: 'Pending',
    status: 'Active',
    joinedDate: new Date('2025-12-15'),
    points: 50,
    nextLevelPoints: 10000,
    totalSpent: 900,
  },
  {
    id: '6',
    name: 'Deepak Mehta',
    email: 'deepak.mehta@email.com',
    phone: '+91 9876543215',
    level: 7,
    levelName: 'Elite',
    avatar: 'D',
    wallet: 22000,
    bonus: 3500,
    tickets: 52,
    referrals: 28,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-12-14'),
    points: 18900,
    nextLevelPoints: 10000,
    totalSpent: 66000,
  },
  {
    id: '7',
    name: 'Ananya Krishna',
    email: 'ananya.krishna@email.com',
    phone: '+91 9876543216',
    level: 6,
    levelName: 'Diamond',
    avatar: 'A',
    wallet: 14500,
    bonus: 2000,
    tickets: 41,
    referrals: 12,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-13'),
    points: 12400,
    nextLevelPoints: 10000,
    totalSpent: 43500,
  },
  {
    id: '8',
    name: 'Vikram Desai',
    email: 'vikram.desai@email.com',
    phone: '+91 9876543217',
    level: 4,
    levelName: 'Gold',
    avatar: 'V',
    wallet: 5100,
    bonus: 600,
    tickets: 28,
    referrals: 5,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-12'),
    points: 3200,
    nextLevelPoints: 10000,
    totalSpent: 15300,
  },
  {
    id: '9',
    name: 'Neha Gupta',
    email: 'neha.gupta@email.com',
    phone: '+91 9876543218',
    level: 3,
    levelName: 'Silver',
    avatar: 'N',
    wallet: 2400,
    bonus: 300,
    tickets: 16,
    referrals: 2,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-11'),
    points: 620,
    nextLevelPoints: 10000,
    totalSpent: 7200,
  },
  {
    id: '10',
    name: 'Rohan Verma',
    email: 'rohan.verma@email.com',
    phone: '+91 9876543219',
    level: 2,
    levelName: 'Bronze',
    avatar: 'R',
    wallet: 1200,
    bonus: 150,
    tickets: 8,
    referrals: 1,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-10'),
    points: 180,
    nextLevelPoints: 10000,
    totalSpent: 3600,
  },
  {
    id: '11',
    name: 'Divya Nair',
    email: 'divya.nair@email.com',
    phone: '+91 9876543220',
    level: 5,
    levelName: 'Platinum',
    avatar: 'D',
    wallet: 9800,
    bonus: 1400,
    tickets: 44,
    referrals: 15,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-12-09'),
    points: 7200,
    nextLevelPoints: 10000,
    totalSpent: 29400,
  },
  {
    id: '12',
    name: 'Sanjay Iyer',
    email: 'sanjay.iyer@email.com',
    phone: '+91 9876543221',
    level: 6,
    levelName: 'Diamond',
    avatar: 'S',
    wallet: 16200,
    bonus: 2200,
    tickets: 48,
    referrals: 18,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-08'),
    points: 14100,
    nextLevelPoints: 10000,
    totalSpent: 48600,
  },
  {
    id: '13',
    name: 'Meera Kapoor',
    email: 'meera.kapoor@email.com',
    phone: '+91 9876543222',
    level: 3,
    levelName: 'Silver',
    avatar: 'M',
    wallet: 2100,
    bonus: 250,
    tickets: 14,
    referrals: 3,
    kycStatus: 'Rejected',
    status: 'Active',
    joinedDate: new Date('2025-12-07'),
    points: 520,
    nextLevelPoints: 10000,
    totalSpent: 6300,
  },
  {
    id: '14',
    name: 'Ajay Reddy',
    email: 'ajay.reddy@email.com',
    phone: '+91 9876543223',
    level: 4,
    levelName: 'Gold',
    avatar: 'A',
    wallet: 6500,
    bonus: 800,
    tickets: 32,
    referrals: 6,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-06'),
    points: 4100,
    nextLevelPoints: 10000,
    totalSpent: 19500,
  },
  {
    id: '15',
    name: 'Pooja Malhotra',
    email: 'pooja.malhotra@email.com',
    phone: '+91 9876543224',
    level: 7,
    levelName: 'Elite',
    avatar: 'P',
    wallet: 25000,
    bonus: 4000,
    tickets: 58,
    referrals: 32,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-12-05'),
    points: 21000,
    nextLevelPoints: 10000,
    totalSpent: 75000,
  },
  {
    id: '16',
    name: 'Rahul Bhat',
    email: 'rahul.bhat@email.com',
    phone: '+91 9876543225',
    level: 2,
    levelName: 'Bronze',
    avatar: 'R',
    wallet: 750,
    bonus: 100,
    tickets: 5,
    referrals: 0,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-04'),
    points: 75,
    nextLevelPoints: 10000,
    totalSpent: 2250,
  },
  {
    id: '17',
    name: 'Swati Deshmukh',
    email: 'swati.deshmukh@email.com',
    phone: '+91 9876543226',
    level: 8,
    levelName: 'Superstar',
    avatar: 'S',
    wallet: 32000,
    bonus: 5000,
    tickets: 72,
    referrals: 45,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-12-03'),
    points: 28500,
    nextLevelPoints: 10000,
    totalSpent: 96000,
  },
  {
    id: '18',
    name: 'Sandeep Chopra',
    email: 'sandeep.chopra@email.com',
    phone: '+91 9876543227',
    level: 1,
    levelName: 'Basic',
    avatar: 'S',
    wallet: 500,
    bonus: 50,
    tickets: 3,
    referrals: 0,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-02'),
    points: 100,
    nextLevelPoints: 10000,
    totalSpent: 1500,
  },
  {
    id: '19',
    name: 'Isha Banerjee',
    email: 'isha.banerjee@email.com',
    phone: '+91 9876543228',
    level: 5,
    levelName: 'Platinum',
    avatar: 'I',
    wallet: 11200,
    bonus: 1600,
    tickets: 48,
    referrals: 20,
    kycStatus: 'Verified',
    status: 'Active',
    joinedDate: new Date('2025-12-01'),
    points: 8400,
    nextLevelPoints: 10000,
    totalSpent: 33600,
  },
  {
    id: '20',
    name: 'Arjun Nambiar',
    email: 'arjun.nambiar@email.com',
    phone: '+91 9876543229',
    level: 9,
    levelName: 'Titan',
    avatar: 'A',
    wallet: 45000,
    bonus: 7000,
    tickets: 95,
    referrals: 62,
    kycStatus: 'Verified',
    status: 'VIP',
    joinedDate: new Date('2025-11-30'),
    points: 42000,
    nextLevelPoints: 10000,
    totalSpent: 135000,
  },
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `${21 + i}`,
    name: ['Gaurav Tiwari', 'Kavya Sinha', 'Nitin Chandra', 'Esha Mishra', 'Harsh Agarwal', 'Zara Khan', 'Rajesh Saxena', 'Simran Arora', 'Vivek Joshi', 'Anushka Sood', 'Nikhil Roy', 'Disha Ahuja', 'Aditya Kulkarni', 'Nia Ghosh', 'Siddharth Rao', 'Ritika Bose', 'Pranav Singh', 'Yara Kapadia', 'Varun Dev', 'Xena Chopra', 'Rishi Malhotra', 'Uvita Nair', 'Tanvi Sharma', 'Sarthak Jain', 'Megha Bhattacharya', 'Kabir Ahmed', 'Nina Patil', 'Jatin Verma', 'Pia Iyengar', 'Ravi Pillai'][i],
    email: `user${21 + i}@email.com`,
    phone: `+91 987654${3230 + i}`,
    level: ((i % 10) + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10,
    levelName: ['Basic', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Elite', 'Superstar', 'Titan', 'VIP'][i % 10],
    avatar: ['Gaurav Tiwari', 'Kavya Sinha', 'Nitin Chandra', 'Esha Mishra', 'Harsh Agarwal', 'Zara Khan', 'Rajesh Saxena', 'Simran Arora', 'Vivek Joshi', 'Anushka Sood', 'Nikhil Roy', 'Disha Ahuja', 'Aditya Kulkarni', 'Nia Ghosh', 'Siddharth Rao', 'Ritika Bose', 'Pranav Singh', 'Yara Kapadia', 'Varun Dev', 'Xena Chopra', 'Rishi Malhotra', 'Uvita Nair', 'Tanvi Sharma', 'Sarthak Jain', 'Megha Bhattacharya', 'Kabir Ahmed', 'Nina Patil', 'Jatin Verma', 'Pia Iyengar', 'Ravi Pillai'][i][0],
    wallet: Math.floor(Math.random() * 50000),
    bonus: Math.floor(Math.random() * 10000),
    tickets: Math.floor(Math.random() * 100),
    referrals: Math.floor(Math.random() * 50),
    kycStatus: ['Verified', 'Pending', 'Rejected'][Math.floor(Math.random() * 3)] as 'Verified' | 'Pending' | 'Rejected',
    status: ['Active', 'Suspended', 'VIP'][Math.floor(Math.random() * 3)] as 'Active' | 'Suspended' | 'VIP',
    joinedDate: new Date(2025, 10, Math.floor(Math.random() * 30) + 1),
    points: Math.floor(Math.random() * 50000),
    nextLevelPoints: 10000,
    totalSpent: Math.floor(Math.random() * 150000),
  })),
];

// Draws Data - 20 draws
export const draws: Draw[] = [
  {
    id: '1',
    name: 'Mega Millions #4821',
    gameType: 'Mega Millions',
    prizePool: 10000000,
    ticketPrice: 100,
    maxEntries: 10000,
    entries: 3241,
    status: 'live',
    drawDate: new Date('2026-02-25T20:30:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Weekly mega draw with jackpot prize pool',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '2',
    name: 'Super Jackpot #219',
    gameType: 'Super Jackpot',
    prizePool: 5000000,
    ticketPrice: 100,
    maxEntries: 5000,
    entries: 1820,
    status: 'scheduled',
    drawDate: new Date('2026-02-26T20:00:00'),
    eligibleLevels: [3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Premium tier draw for mid-level players',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '3',
    name: 'Power Ball #88',
    gameType: 'Power Ball',
    prizePool: 2500000,
    ticketPrice: 50,
    maxEntries: 8000,
    entries: 7240,
    status: 'completed',
    drawDate: new Date('2026-02-24T20:30:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Daily power ball draw',
    winnerId: '4421',
    winnerName: 'Raj Kumar',
  },
  {
    id: '4',
    name: 'Daily Premium #485',
    gameType: 'Daily Draw',
    prizePool: 500000,
    ticketPrice: 50,
    maxEntries: 3000,
    entries: 1540,
    status: 'scheduled',
    drawDate: new Date('2026-02-26T18:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Daily afternoon draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '5',
    name: 'VIP Exclusive #142',
    gameType: 'VIP Only',
    prizePool: 3000000,
    ticketPrice: 500,
    maxEntries: 500,
    entries: 289,
    status: 'live',
    drawDate: new Date('2026-02-25T22:00:00'),
    eligibleLevels: [8, 9, 10],
    description: 'Exclusive draw for VIP members only',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '6',
    name: 'Lucky 7 #920',
    gameType: 'Weekly Draw',
    prizePool: 1500000,
    ticketPrice: 100,
    maxEntries: 4000,
    entries: 3120,
    status: 'scheduled',
    drawDate: new Date('2026-02-28T20:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Weekly lucky draw with 7 winners',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '7',
    name: 'Gold Rush #201',
    gameType: 'Hourly Draw',
    prizePool: 100000,
    ticketPrice: 100,
    maxEntries: 1000,
    entries: 845,
    status: 'completed',
    drawDate: new Date('2026-02-25T14:00:00'),
    eligibleLevels: [4, 5, 6, 7, 8, 9, 10],
    description: 'Hourly draw for gold and above members',
    winnerId: '2145',
    winnerName: 'Priya Sharma',
  },
  {
    id: '8',
    name: 'Standard Draw #556',
    gameType: 'Standard',
    prizePool: 800000,
    ticketPrice: 50,
    maxEntries: 5000,
    entries: 4520,
    status: 'live',
    drawDate: new Date('2026-02-25T19:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Standard daily draw for all members',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '9',
    name: 'Platinum Elite #77',
    gameType: 'Premium',
    prizePool: 2000000,
    ticketPrice: 200,
    maxEntries: 2000,
    entries: 1340,
    status: 'scheduled',
    drawDate: new Date('2026-02-27T21:00:00'),
    eligibleLevels: [5, 6, 7, 8, 9, 10],
    description: 'Premium draw for platinum and above',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '10',
    name: 'Bronze Basic #333',
    gameType: 'Entry Level',
    prizePool: 250000,
    ticketPrice: 50,
    maxEntries: 2000,
    entries: 1890,
    status: 'completed',
    drawDate: new Date('2026-02-23T18:30:00'),
    eligibleLevels: [1, 2, 3],
    description: 'Entry level draw for new members',
    winnerId: '1520',
    winnerName: 'Amit Singh',
  },
  {
    id: '11',
    name: 'Mega Spin #102',
    gameType: 'Mega Millions',
    prizePool: 8000000,
    ticketPrice: 150,
    maxEntries: 6000,
    entries: 5240,
    status: 'draft',
    drawDate: new Date('2026-03-05T20:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Upcoming mega spin draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '12',
    name: 'Quick Pick #667',
    gameType: 'Quick Draw',
    prizePool: 300000,
    ticketPrice: 100,
    maxEntries: 1500,
    entries: 1200,
    status: 'completed',
    drawDate: new Date('2026-02-22T16:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Quick daily draw',
    winnerId: '3850',
    winnerName: 'Sneha Patel',
  },
  {
    id: '13',
    name: 'Progressive Jackpot #44',
    gameType: 'Progressive',
    prizePool: 12000000,
    ticketPrice: 200,
    maxEntries: 8000,
    entries: 6780,
    status: 'live',
    drawDate: new Date('2026-02-25T21:30:00'),
    eligibleLevels: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Progressive jackpot with accumulated prizes',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '14',
    name: 'Diamond Dash #55',
    gameType: 'Premium',
    prizePool: 4000000,
    ticketPrice: 300,
    maxEntries: 3000,
    entries: 2450,
    status: 'scheduled',
    drawDate: new Date('2026-03-01T20:00:00'),
    eligibleLevels: [6, 7, 8, 9, 10],
    description: 'Diamond tier exclusive draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '15',
    name: 'Starter Set #811',
    gameType: 'Entry Level',
    prizePool: 150000,
    ticketPrice: 50,
    maxEntries: 1000,
    entries: 920,
    status: 'completed',
    drawDate: new Date('2026-02-21T17:00:00'),
    eligibleLevels: [1, 2],
    description: 'Starter draw for new members',
    winnerId: '820',
    winnerName: 'Kiran Rao',
  },
  {
    id: '16',
    name: 'Flash Sale #99',
    gameType: 'Flash Draw',
    prizePool: 500000,
    ticketPrice: 100,
    maxEntries: 2000,
    entries: 1650,
    status: 'scheduled',
    drawDate: new Date('2026-02-26T15:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Limited time flash draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '17',
    name: 'Elite Endurance #123',
    gameType: 'Premium',
    prizePool: 6000000,
    ticketPrice: 250,
    maxEntries: 5000,
    entries: 4120,
    status: 'live',
    drawDate: new Date('2026-02-25T23:00:00'),
    eligibleLevels: [7, 8, 9, 10],
    description: 'Elite multi-winner draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '18',
    name: 'Silver Surprise #456',
    gameType: 'Standard',
    prizePool: 1200000,
    ticketPrice: 100,
    maxEntries: 4000,
    entries: 3560,
    status: 'scheduled',
    drawDate: new Date('2026-02-27T19:30:00'),
    eligibleLevels: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Silver level and above draw',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '19',
    name: 'Championship #789',
    gameType: 'Mega Millions',
    prizePool: 15000000,
    ticketPrice: 300,
    maxEntries: 10000,
    entries: 8900,
    status: 'scheduled',
    drawDate: new Date('2026-03-10T20:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Championship draw with massive jackpot',
    winnerId: undefined,
    winnerName: undefined,
  },
  {
    id: '20',
    name: 'Bonus Barrel #200',
    gameType: 'Bonus Draw',
    prizePool: 1000000,
    ticketPrice: 100,
    maxEntries: 3500,
    entries: 2780,
    status: 'completed',
    drawDate: new Date('2026-02-20T20:00:00'),
    eligibleLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    description: 'Extra bonus prizes draw',
    winnerId: '5500',
    winnerName: 'Deepak Mehta',
  },
];

// Transactions Data - 100 transactions
export const transactions: Transaction[] = Array.from({ length: 100 }, (_, i) => ({
  id: `TXN${String(8821 + i).padStart(5, '0')}`,
  userId: String((i % 20) + 1),
  userName: ['Ravi Kumar', 'Priya Sharma', 'Amit Singh', 'Sneha Patel', 'Kiran Rao', 'Deepak Mehta', 'Ananya Krishna', 'Vikram Desai', 'Neha Gupta', 'Rohan Verma', 'Divya Nair', 'Sanjay Iyer', 'Meera Kapoor', 'Ajay Reddy', 'Pooja Malhotra', 'Rahul Bhat', 'Swati Deshmukh', 'Sandeep Chopra', 'Isha Banerjee', 'Arjun Nambiar'][i % 20],
  method: ['UPI', 'Card', 'NetBanking', 'Wallet'][i % 4] as 'UPI' | 'Card' | 'NetBanking' | 'Wallet',
  amount: Math.floor(Math.random() * 50000) + 100,
  type: ['Deposit', 'Withdrawal', 'TicketPurchase', 'PrizePayout'][i % 4] as 'Deposit' | 'Withdrawal' | 'TicketPurchase' | 'PrizePayout',
  status: ['Success', 'Pending', 'Failed'][Math.floor(Math.random() * 3)] as 'Success' | 'Pending' | 'Failed',
  datetime: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000),
  note: ['Payment received', 'Cashout requested', 'Ticket purchased', 'Prize payout'][i % 4],
}));

// KYC Documents - 8 pending
export const kycDocuments: KYCDocument[] = [
  {
    id: '1',
    userId: '5',
    userName: 'Kiran Rao',
    email: 'kiran.rao@email.com',
    docType: 'Aadhaar',
    submittedAt: new Date('2026-02-25T10:30:00'),
    docUrl: 'https://placeholder.com/kyc/aadhaar_1.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_1.jpg',
  },
  {
    id: '2',
    userId: '13',
    userName: 'Meera Kapoor',
    email: 'meera.kapoor@email.com',
    docType: 'PAN',
    submittedAt: new Date('2026-02-25T11:15:00'),
    docUrl: 'https://placeholder.com/kyc/pan_2.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_2.jpg',
  },
  {
    id: '3',
    userId: '24',
    userName: 'Sarthak Jain',
    email: 'sarthak.jain@email.com',
    docType: 'Passport',
    submittedAt: new Date('2026-02-25T12:00:00'),
    docUrl: 'https://placeholder.com/kyc/passport_3.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_3.jpg',
  },
  {
    id: '4',
    userId: '31',
    userName: 'Pia Iyengar',
    email: 'pia.iyengar@email.com',
    docType: 'VoterID',
    submittedAt: new Date('2026-02-25T13:45:00'),
    docUrl: 'https://placeholder.com/kyc/voterid_4.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_4.jpg',
  },
  {
    id: '5',
    userId: '8',
    userName: 'Vikram Desai',
    email: 'vikram.desai@email.com',
    docType: 'Aadhaar',
    submittedAt: new Date('2026-02-24T14:20:00'),
    docUrl: 'https://placeholder.com/kyc/aadhaar_5.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_5.jpg',
  },
  {
    id: '6',
    userId: '16',
    userName: 'Rahul Bhat',
    email: 'rahul.bhat@email.com',
    docType: 'PAN',
    submittedAt: new Date('2026-02-24T15:30:00'),
    docUrl: 'https://placeholder.com/kyc/pan_6.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_6.jpg',
  },
  {
    id: '7',
    userId: '28',
    userName: 'Jatin Verma',
    email: 'jatin.verma@email.com',
    docType: 'Passport',
    submittedAt: new Date('2026-02-24T16:00:00'),
    docUrl: 'https://placeholder.com/kyc/passport_7.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_7.jpg',
  },
  {
    id: '8',
    userId: '38',
    userName: 'Xena Chopra',
    email: 'xena.chopra@email.com',
    docType: 'Aadhaar',
    submittedAt: new Date('2026-02-24T17:15:00'),
    docUrl: 'https://placeholder.com/kyc/aadhaar_8.jpg',
    selfieUrl: 'https://placeholder.com/kyc/selfie_8.jpg',
  },
];

// Notifications
export const notifications: Notification[] = Array.from({ length: 20 }, (_, i) => ({
  id: `NOTIF${String(1001 + i).padStart(4, '0')}`,
  icon: ['🎯', '🏆', '⬆️', '💰', '👥', '🔔'][i % 6],
  title: ['Draw Started', 'Winner Announced', 'Level Up Alert', 'Wallet Credited', 'Referral Joined', 'Special Offer'][i % 6],
  audience: ['All Users', 'Level 5+', 'Inactive', 'VIP Only', 'Gold+', 'New Users'][i % 6],
  channels: [['Push', 'Email'], ['Email', 'SMS'], ['Push'], ['Push', 'Email', 'SMS'], ['Email'], ['Push', 'SMS']][i % 6],
  sentCount: Math.floor(Math.random() * 50000) + 1000,
  openRate: Math.floor(Math.random() * 100),
  clickRate: Math.floor(Math.random() * 100),
  sentAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
  status: ['Sent', 'Draft', 'Scheduled'][i % 3],
}));

// Admin Logs
export const adminLogs: AdminLog[] = [
  {
    id: '1',
    adminName: 'Admin User',
    action: 'Approved KYC',
    target: 'User #4821 - Ravi Kumar',
    datetime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    ip: '192.168.1.105',
  },
  {
    id: '2',
    adminName: 'Admin Manager',
    action: 'Suspended Account',
    target: 'User #3421 - Test User',
    datetime: new Date(Date.now() - 4 * 60 * 60 * 1000),
    ip: '192.168.1.108',
  },
  {
    id: '3',
    adminName: 'Admin User',
    action: 'Created Draw',
    target: 'Draw #4822 - Mega Millions',
    datetime: new Date(Date.now() - 6 * 60 * 60 * 1000),
    ip: '192.168.1.105',
  },
  {
    id: '4',
    adminName: 'Admin Super',
    action: 'Updated Referral Reward',
    target: 'Referral Program',
    datetime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.100',
  },
  {
    id: '5',
    adminName: 'Admin User',
    action: 'Exported User Data',
    target: 'CSV Export - 100 users',
    datetime: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.105',
  },
  {
    id: '6',
    adminName: 'Admin Manager',
    action: 'Sent Notification',
    target: 'Draw Started to 24,891 users',
    datetime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.108',
  },
  {
    id: '7',
    adminName: 'Admin User',
    action: 'Rejected KYC',
    target: 'User #2145 - Priya Sharma',
    datetime: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.105',
  },
  {
    id: '8',
    adminName: 'Admin Super',
    action: 'Adjusted User Wallet',
    target: 'User #5500 - Deepak Mehta: +₹5000',
    datetime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.100',
  },
  {
    id: '9',
    adminName: 'Admin Manager',
    action: 'Updated Level Config',
    target: 'Level 5 - Platinum',
    datetime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.108',
  },
  {
    id: '10',
    adminName: 'Admin User',
    action: 'Completed Draw',
    target: 'Draw #88 - Power Ball',
    datetime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    ip: '192.168.1.105',
  },
];

// Level Configuration
export const levelConfig: Level[] = [
  {
    level: 1,
    name: 'Basic Member',
    color: '#4a5568',
    users: 12480,
    pointsMin: 0,
    pointsMax: 99,
    perks: ['1 number pick', 'Standard tickets'],
    discount: 0,
    picks: 1,
  },
  {
    level: 2,
    name: 'Bronze',
    color: '#cd7c2f',
    users: 5240,
    pointsMin: 100,
    pointsMax: 299,
    perks: ['2 picks', '5% discount', 'Basic referral bonus'],
    discount: 5,
    picks: 2,
  },
  {
    level: 3,
    name: 'Silver',
    color: '#94a3b8',
    users: 3820,
    pointsMin: 300,
    pointsMax: 599,
    perks: ['3 picks', '10% discount', 'Priority email support'],
    discount: 10,
    picks: 3,
  },
  {
    level: 4,
    name: 'Gold',
    color: '#f5c518',
    users: 2140,
    pointsMin: 600,
    pointsMax: 999,
    perks: ['4 picks', '15% discount', 'Enhanced referral rewards'],
    discount: 15,
    picks: 4,
  },
  {
    level: 5,
    name: 'Platinum',
    color: '#00d68f',
    users: 980,
    pointsMin: 1000,
    pointsMax: 1999,
    perks: ['5 picks', '20% discount', 'Priority support', 'Early access'],
    discount: 20,
    picks: 5,
  },
  {
    level: 6,
    name: 'Diamond',
    color: '#06b6d4',
    users: 420,
    pointsMin: 2000,
    pointsMax: 4999,
    perks: ['6 picks', '25% discount', 'Analytics dashboard'],
    discount: 25,
    picks: 6,
  },
  {
    level: 7,
    name: 'Elite',
    color: '#a855f7',
    users: 280,
    pointsMin: 5000,
    pointsMax: 9999,
    perks: ['7 picks', '30% discount', 'Dedicated VIP support'],
    discount: 30,
    picks: 7,
  },
  {
    level: 8,
    name: 'Superstar',
    color: '#f59e0b',
    users: 188,
    pointsMin: 10000,
    pointsMax: 19999,
    perks: ['8 picks', '35% discount', 'Personal account manager'],
    discount: 35,
    picks: 8,
  },
  {
    level: 9,
    name: 'Titan',
    color: '#3d9eff',
    users: 94,
    pointsMin: 20000,
    pointsMax: 49999,
    perks: ['9 picks', '40% discount', 'Exclusive Titan draws'],
    discount: 40,
    picks: 9,
  },
  {
    level: 10,
    name: 'VIP',
    color: '#f5c518',
    users: 52,
    pointsMin: 50000,
    pointsMax: 999999,
    perks: ['Unlimited picks', '50% discount', 'All perks', 'Concierge service'],
    discount: 50,
    picks: 999,
  },
];

// Points Earning Rules
export interface PointsRule {
  id: string;
  action: string;
  points: number;
  description: string;
  editable: boolean;
}

export const pointsRules: PointsRule[] = [
  {
    id: '1',
    action: 'Ticket Purchase',
    points: 10,
    description: '10 points per ₹100 spent',
    editable: true,
  },
  {
    id: '2',
    action: 'Referral Signup',
    points: 50,
    description: '50 points per successful referral',
    editable: true,
  },
  {
    id: '3',
    action: 'Win Draw',
    points: 200,
    description: '200 points for winning any draw',
    editable: true,
  },
  {
    id: '4',
    action: 'Daily Login',
    points: 5,
    description: '5 points per day login streak',
    editable: true,
  },
  {
    id: '5',
    action: 'Wallet Top-up',
    points: 5,
    description: '5 points per ₹100 deposited',
    editable: true,
  },
  {
    id: '6',
    action: 'Social Share',
    points: 10,
    description: '10 points per verified social share',
    editable: true,
  },
];

// Wallet Data
export interface WalletData {
  userId: string;
  userName: string;
  balance: number;
  bonus: number;
  locked: number;
  lastTxn: string;
}

export const walletData: WalletData[] = users.slice(0, 20).map((user) => ({
  userId: user.id,
  userName: user.name,
  balance: user.wallet,
  bonus: user.bonus,
  locked: Math.floor(Math.random() * 10000),
  lastTxn: ['2h ago', '5h ago', '1d ago', '2d ago', '3d ago'][Math.floor(Math.random() * 5)],
}));
